# Include variable and secrets based on type of environment
# all is available across
- include_vars: ../../../../../../group_vars/vault.yml
  no_log: false
  when: env_ver == "new-vpc"
- include_vars: ../../../../../../group_vars/vault.yml
  no_log: false
  when: env_ver == "existing-vpc"

## Varibale for New vpc ( Dio and Marvel Project)
- include_vars: ../../../../../../group_vars/Dio/new-vpc.yml
  no_log: false
  when: env_ver == "new-vpc" and project == "dio"

- include_vars: ../../../../../../group_vars/Marvel/new-vpc.yml
  no_log: false
  when: env_ver == "new-vpc" and project == "marvel"

## Varibale for Existing vpc ( Dio and Marvel Project)

- include_vars: ../../../../../../group_vars/Dio/existing-vpc.yml
  no_log: false
  when: env_ver == "existing-vpc" and project == "dio"

- include_vars: ../../../../../../group_vars/Marvel/existing-vpc.yml
  no_log: false
  when: env_ver == "existing-vpc" and project == "marvel"


# Create VPC for Monitoing Box
- name: Alertmanager
  cloudformation:
    stack_name: "{{stack_prefix}}-alertmanager"
    state: "present"
    region: "{{cluster_region}}"
    disable_rollback: false
    template_format: yaml
    validate_certs: no
    template: "{{ role_path }}/ecs/services/alertmanager/template/service.yaml"
    #Capabilities.member.N: yes
    #role_arn: arn:aws:iam::939393939339:role/monitoring
    template_parameters:
      VPC: "{{vpc_id}}"
      Cluster: "{{cluster}}"
      Listener: "{{listener}}"
      Alertmanagerurl: "{{alertmanager_url}}"
      AlertmanagerImage: "{{alertmanager_image}}"
      AlertmanagerCpu: "{{alertmanager_cpu}}"
      AlertmanagerMemory: "{{alertmanager_mem}}"
      AlertFrom: "{{alert_from}}"
      SmtpAddress: "{{smtp_address}}"
    tags:
      Stack: "{{stack_name}}"
  register: alertmanager_stack
