# Include variable and secrets based on type of environment
# all is available across
- include_vars: ../../../../../../group_vars/vault.yml
  no_log: false
  when: env_ver == "new-vpc"
- include_vars: ../../../../../../group_vars/vault.yml
  no_log: false
  when: env_ver == "existing-vpc"

## Varibale for New vpc ( Dio and Marvel Project)
- include_vars: ../../../../../../group_vars/Dio/new-vpc.yml
  no_log: false
  when: env_ver == "new-vpc" and project == "dio"

- include_vars: ../../../../../../group_vars/Marvel/new-vpc.yml
  no_log: false
  when: env_ver == "new-vpc" and project == "marvel"

## Varibale for Existing vpc ( Dio and Marvel Project)

- include_vars: ../../../../../../group_vars/Dio/existing-vpc.yml
  no_log: false
  when: env_ver == "existing-vpc" and project == "dio"

- include_vars: ../../../../../../group_vars/Marvel/existing-vpc.yml
  no_log: false
  when: env_ver == "existing-vpc" and project == "marvel"


# Create VPC for Monitoing Box
- name: Prometheus
  cloudformation:
    stack_name: "{{stack_prefix}}-prometheus"
    state: "present"
    region: "{{cluster_region}}"
    disable_rollback: false
    template_format: yaml
    validate_certs: no
    template: "{{ role_path }}/ecs/services/prometheus/template/service.yaml"
    #Capabilities.member.N: yes
    #role_arn: arn:aws:iam::939393939339:role/monitoring
    template_parameters:
      VPC: "{{vpc_id}}"
      Cluster: "{{cluster}}"
      Listener: "{{listener}}"
      Prometheusurl: "{{prometheus_url}}"
      PrometheusSourceVolume: "{{prometheus_volume}}"
      PrometheusContainerPath: "{{prometheus_volume_path}}"
      PrometheusSourcePath: "{{prometheus_volume_source_path}}"
      kubecluster: "{{kubernetes_api_url}}"
      kubeclusterport: "{{kubernetes_api_port}}"
      PrometheusCpu: "{{prometheus_cpu}}"
      PrometheusMemory: "{{prometheus_mem}}"
      PrometheusImage: "{{prometheus_image}}"
    tags:
      Stack: "{{stack_name}}"
  register: prometheus_stack
