task_family: "kongperf-SERVICES"
task_role_arn: ''
network_mode: "bridge"
c1_appname: kongperf
c1_cpu: 200
c1_memory: 2048
c1_soft_memory: 512
c1_ports:
  - c1hostPort: 0
    c1containerPort: 8080
    c1protocol: tcp
c1_image: 939393939339.dkr.ecr.us-east-1.amazonaws.com/kong-performance-test
c1_essential: True
c1_privileged: False
c1_environment_variables:
  - c1name : APP_ENV
    c1value: env_properties
  - c1name : CONF_HOME
    c1value: /opt/apps-java/config
c1_awslogs_group: "/aws/ecs/{{env}}"
c1_log_region: us-east-2
c1_awslogs_stream_prefix: kongperf-logs
c1_docker_labels: kongperf-containers
c1_docker_security_options: no-new-privileges


# Service Setup
cluster_name: "Application-Cluster-{{env}}"
service_name: "kongperf-services"
count: "2"

# Stage to Prod it has to be rolling update
maximumPercent: 200
minimumHealthyPercent: 50
