task_family: "DOTNET-SERVICES"
task_role_arn: ''
network_mode: "bridge"
c1_appname: dotnet
c1_cpu: 1024
c1_memory: 2048
c1_soft_memory: 512
c1_ports:
  - c1hostPort: 80
    c1containerPort: 80
    c1protocol: tcp
c1_image: 939393939339.dkr.ecr.us-east-1.amazonaws.com/{{ ecr_prefix }}-dotnet:{{ build_no | default ('latest')}}
c1_essential: True
c1_privileged: False
c1_environment_variables:
  - c1name : APP_ENV
    c1value: env_properties
    # Using master token for now. Once we have valut, we can change this
  - c1name : container_name
    c1value: "dotnet-containers"
  - c1name : namespace
    c1value: "plp-{{env}}"
  - c1name : service_name
    c1value: "dotnet-{{env}}-service"
  - c1name : container_id
    c1value: "dotnet-container-{{env}}"
  - c1name : host
    c1value: "dotnet.weave.local"
c1_awslogs_group: Application-logs-{{env}}
c1_log_region: ap-southeast-2
c1_awslogs_stream_prefix: dotnet-service-logs
c1_docker_labels: dotnet-containers
c1_docker_security_options: no-new-privileges
# Service Setup
cluster_name: "Application-Cluster-{{env}}"
service_name: "dotnet-services"
count: "2"

# Stage to Prod it has to be rolling update
maximumPercent: 200
minimumHealthyPercent: 50
