task_family: "PROMETHEUS"
task_role_arn: ''
network_mode: "bridge"
c1_appname: prometheus
c1_cpu: 6144
c1_memory: 16384
c1_soft_memory: 16384
c1_ports:
  - c1hostPort: 9090
    c1containerPort: 9090
    c1protocol: tcp
c1_image: 939393939339.dkr.ecr.us-east-1.amazonaws.com/prometheus_2.0.0:{{ build_no | default ('latest')}}
c1_essential: True
c1_privileged: False
c1_environment_variables:
  - c1name : REGION
    c1value: eu-west-1
  - c1name : MICROSERVICE_ENDPOINT
    c1value: "consul.{{env}}-internal.com"
  - c1name : RETENTION_TIME
    c1value: 3h
  - c1name : ALERTMANAGER_ADDRESS
    c1value: alertmanager.weave.local
  - c1name : ENVIRONMENT
    c1value: PLP-{{env}}-Environment-
  # Using master token for now. Once we have valut, we can change this
c1_awslogs_group: Monitoring-logs-{{env}}
c1_log_region: ap-southeast-2
c1_awslogs_stream_prefix: prometheus-service-logs
c1_docker_labels: prometheus-containers
c1_docker_security_options: no-new-privileges


# Volume attachment

src_volume_name: "data"
volume_src_path: "/prometheus_data"
mount_container_path: "/prometheus"
mount_readonly_bool: False



# Service Setup
cluster_name: "Monitoring-Cluster-{{env}}"
service_name: "prometheus"
count: "1"

# Stage to Prod it has to be rolling update
maximumPercent: 200
minimumHealthyPercent: 100
