---
# This will register our zookeeper instance with our private domain
# - name: Update Route53 entries for zookeeper
#   route53:
#        command: create
#        zone: "{{env}}-internal.com"
#        record: "zookeeper.{{env}}-internal.com"
#        type: A
#        ttl: 300
#        value: "{% for host in groups['tag_Role2_zookeeper_instances'] %}{{ hostvars[host]['ansible_ssh_host']}}{% if not loop.last %},{% endif %}{% endfor %}"
#        overwrite: true
#        private_zone: true
- hosts: localhost
  gather_facts: False
  become: False
  tasks:
  - name: Update Route53 entries for Couchbase
    route53:
       command: create
       zone: "{{env}}-internal.com"
       record: couchbase.{{env}}-internal.com
       type: A
       ttl: 30
       value: "{% for host in groups['tag_Role_couchbase'] %}{{ hostvars[host]['ansible_ssh_host']}}{% if not loop.last %},{% endif %}{% endfor %}"
       overwrite: true
       private_zone: true
