# Include variable and secrets based on type of environment
# all is available across
- include_vars: ../../../../../../group_vars/vault.yml
  no_log: false
  when: env_ver == "new-vpc"
- include_vars: ../../../../../../group_vars/vault.yml
  no_log: false
  when: env_ver == "existing-vpc"

## Varibale for New vpc ( Dio and Marvel Project)
- include_vars: ../../../../../../group_vars/Dio/new-vpc.yml
  no_log: false
  when: env_ver == "new-vpc" and project == "dio"

- include_vars: ../../../../../../group_vars/Marvel/new-vpc.yml
  no_log: false
  when: env_ver == "new-vpc" and project == "marvel"

## Varibale for Existing vpc ( Dio and Marvel Project)

- include_vars: ../../../../../../group_vars/Dio/existing-vpc.yml
  no_log: false
  when: env_ver == "existing-vpc" and project == "dio"

- include_vars: ../../../../../../group_vars/Marvel/existing-vpc.yml
  no_log: false
  when: env_ver == "existing-vpc" and project == "marvel"




# Create VPC for Monitoing Box
- name: Mysql
  cloudformation:
    stack_name: "{{stack_prefix}}-mysql"
    state: "present"
    region: "{{cluster_region}}"
    disable_rollback: false
    template_format: yaml
    validate_certs: no
    template: "{{ role_path }}/ecs/services/mysql/template/service.yaml"
    #Capabilities.member.N: yes
    #role_arn: arn:aws:iam::939393939339:role/monitoring
    template_parameters:
      VPC: "{{vpc_id}}"
      Cluster: "{{cluster}}"
      Listener: "{{listener}}"
      MysqlSourceVolume: "{{mysql_volume}}"
      MysqlContainerPath: "{{mysql_volume_path}}"
      MysqlSourcePath: "{{mysql_volume_source_path}}"
      MysqlrootPass: "{{mysql_root_pass}}"
      MysqlDBName: "{{mysql_db_name}}"
      MysqlCpu: "{{mysql_cpu}}"
      MysqlMemory: "{{mysql_mem}}"
      MysqlImage: "{{mysql_image}}"
    tags:
      Stack: "{{stack_name}}"
  register: mysql_stack
