# Create consul token secret
- include_vars: ../../group_vars/vault.yml
  no_log: true
  when: platform == "kubernetes"

# - set_fact:
#     postgres_password: "postgres_passwd_{{env}}"
#     cb_admin: "cb_admin_{{env}}"


- name: Create Grafana Secrets
  k8s_v1_secret:
    name: "grafana-admin-password"
    name: "mysql-admin-password"
    namespace: "{{ns_name}}"
    data:
       postgresPasswd: "{{postgres_passwd_common | b64encode }}"
    kubeconfig: "{{ '~' | expanduser }}/.kube/config"
    state: "{{status}}"

- name: Create kongui secret
  k8s_v1_secret:
    name: "kongui-password"
    namespace: "{{ns_name}}"
    data:
       konguiPasswd: "{% for item in kongui_passwd %}{% if item == env %}{{kongui_passwd[item] | b64encode }}{% endif %}{% endfor %}"
    kubeconfig: "{{ '~' | expanduser }}/.kube/config"
    state: "{{status}}"

# - name: Create kong ssl secret
#   k8s_v1_secret:
#     name: "kong-key-crt"
#     namespace: "{{ns_name}}"
#     data:
#        kong-custom.crt: "{{kong_ssl_crt| b64encode }}"
#        kong-custom.key: "{{kong_ssl_key| b64encode }}"
#     kubeconfig: "{{ '~' | expanduser }}/.kube/config"
#     state: "{{status}}"

- name: Create couchbase secret
  k8s_v1_secret:
    name: "couchbase-password"
    namespace: "{{ns_name}}"
    data:
       couchbase.password: "{% for item in cbadmin_passwd %}{% if item == env %}{{cbadmin_passwd[item] | b64encode }}{% endif %}{% endfor %}"
    kubeconfig: "{{ '~' | expanduser }}/.kube/config"
    state: "{{status}}"

- name: Create couchbase bucket secret
  k8s_v1_secret:
    name: "cb-bkt-passwd"
    namespace: "{{ns_name}}"
    data:
       bktKernel: "{{ bkt_cb_kernel | b64encode }}"
       bktEses: "{{ bkt_cb_eses | b64encode }}"
       bktAnalytics: "{{ bkt_cb_analytics | b64encode }}"
    kubeconfig: "{{ '~' | expanduser }}/.kube/config"
    state: "{{status}}"

- name: Create consul secret
  k8s_v1_secret:
    name: "consul-token"
    namespace: "{{ns_name}}"
    data:
       consul-token: "{{consul_token | b64encode }}"
    kubeconfig: "{{ '~' | expanduser }}/.kube/config"
    state: "{{status}}"

- name: Create s3 bucket secret
  k8s_v1_secret:
    name: "s3-bucket-creds"
    namespace: "{{ns_name}}"
    data:
       aws-s3-key-id: "{{s3_key | b64encode}}"
       aws-s3-secret-key: "{{s3_secret_key | b64encode }}"
    kubeconfig: "{{ '~' | expanduser }}/.kube/config"
    state: "{{status}}"
